// Runs in GitHub Actions: generates today's content plan and opens an issue.
// Zero platform APIs touched — this automates YOUR morning routine, nothing else.
import { loadConfig, todayStr } from '../src/util.js';
import { generateIdeas } from '../src/ideas.js';

const token = process.env.GITHUB_TOKEN;
const repo = process.env.GITHUB_REPOSITORY;
if (!token || !repo) {
  console.error('GITHUB_TOKEN and GITHUB_REPOSITORY are required (run me inside Actions).');
  process.exit(1);
}

const config = loadConfig();
const date = todayStr();
const ideas = generateIdeas(config, date, 3);

const lines = [
  `Daily content plan for **${config.site.name}** — generated by social-butterfly.`,
  '',
];
for (const idea of ideas) {
  lines.push(`## ${idea.headline ? '⭐' : '💡'} ${idea.pillarLabel} — ${idea.hook}`);
  lines.push('');
  lines.push(`**Platforms:** ${idea.platforms.join(', ')} · **Effort:** ${idea.effort}`);
  lines.push(`**Asset:** ${idea.asset}`);
  lines.push('');
  for (const platform of idea.platforms) {
    const cap = idea.captions[platform];
    const text = cap?.text ?? (cap?.title ? `**${cap.title}**\n\n${cap.description ?? ''}` : '');
    lines.push(`<details><summary>${platform} caption</summary>`);
    lines.push('');
    lines.push('```');
    lines.push(text.trim());
    lines.push('```');
    lines.push('</details>');
    lines.push('');
  }
}
lines.push('---');
lines.push('- [ ] capture media (`npm run capture -- --record 20`)');
lines.push('- [ ] post the ⭐ idea (then `node bin/butterfly.js done <id>`)');
lines.push('- [ ] reply to every comment within the first hour');
lines.push('');
lines.push('_Close this issue when done. Posting stays manual on purpose — see docs/SAFE_AUTOMATION.md._');

const res = await fetch(`https://api.github.com/repos/${repo}/issues`, {
  method: 'POST',
  headers: {
    authorization: `Bearer ${token}`,
    accept: 'application/vnd.github+json',
    'content-type': 'application/json',
  },
  body: JSON.stringify({
    title: `📅 Content plan — ${date}`,
    body: lines.join('\n'),
    labels: ['content-plan'],
  }),
});

if (!res.ok) {
  console.error(`GitHub API error ${res.status}: ${await res.text()}`);
  process.exit(1);
}
const issue = await res.json();
console.log(`✓ opened ${issue.html_url}`);
